NotaVenta/Controllers/ReporteController.cs
using NotaVenta.UTIL;
using NotaVenta.UTIL.FilterAttributes;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using UTIL;
using UTIL.Models;
using UTIL.Objetos;

namespace TexasHub.Controllers
{
    public class ReporteController : BaseController
    {
        #region Nota de Venta

        #region Vistas

        public ActionResult Index()
        {
            return null;
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.ADMINISTRADOR, PERFILES.APROBADOR, PERFILES.VENDEDOR)]
        public ActionResult FacturasPendientes()
        {
            ParametrosModels parametros = ObtieneParametros();

            ViewBag.Parametros = parametros;

            List<NotadeVentaCabeceraModels> doc = new List<NotadeVentaCabeceraModels>();
            string codigoVendedor = obtenerUsuario().TipoUsuario == Convert.ToInt32(PERFILES.APROBADOR) ? "-1" : codigoVendedorUsuario();
            var docPendientes = controlDisofi().listarDocPendientes(baseDatosUsuario(), EmpresaUsuario().IdEmpresa, codigoVendedor);

            if (docPendientes != null)
            {
                doc = docPendientes;
            }

            foreach (var item in doc)
            {
                for (int i = 0; i < doc.Count; i++)
                {
                    List<SaldosModel> Saldos = new List<SaldosModel>();
                    Saldos = controlDisofi().ObtenerSaldo(doc[i].RutAux, doc[i].CodAux, baseDatosUsuario());
                    if (Saldos != null && Saldos.Count > 0)
                    {
                        doc[i].Saldo = 0;
                        foreach (SaldosModel itemSaldo in Saldos)
                        {
                            doc[i].Saldo = doc[i].Saldo + itemSaldo.Saldo;
                        }
                    }
                }
            }


            ViewBag.doc = doc;


            ViewBag.Monedas = controlDisofi().ListarMonedas(baseDatosUsuario());
            ViewBag.Grupos = controlDisofi().ListarGrupos(baseDatosUsuario());
            ViewBag.SubGrupos = controlDisofi().ListarSubGrupos(baseDatosUsuario());

            return View();
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.ADMINISTRADOR, PERFILES.APROBADOR, PERFILES.VENDEDOR)]
        public ActionResult FacturasRechazadas()
        {
            ParametrosModels parametros = ObtieneParametros();

            ViewBag.Parametros = parametros;
            List<NotadeVentaCabeceraModels> doc = new List<NotadeVentaCabeceraModels>();
            string codigoVendedor = obtenerUsuario().TipoUsuario == Convert.ToInt32(PERFILES.APROBADOR) ? "-1" : codigoVendedorUsuario();
            var docPendientes = controlDisofi().listarDocRechazadas(baseDatosUsuario(), EmpresaUsuario().IdEmpresa, codigoVendedor);

            if (docPendientes != null)
            {
                doc = docPendientes;
            }

            ViewBag.doc = doc;

            return View();
        }

        [HttpPost]
        public JsonResult FacturasPendientes(int _nvId)
        {
            NotadeVentaCabeceraModels NVC = new NotadeVentaCabeceraModels();
            List<NotadeVentaCabeceraModels> NVCL = new List<NotadeVentaCabeceraModels>();
            NotaDeVentaDetalleModels NVD = new NotaDeVentaDetalleModels();
            List<NotaDeVentaDetalleModels> NVDL = new List<NotaDeVentaDetalleModels>();

            NVC.Id = _nvId;
            NVD.Id = _nvId;

            var nvc = controlDisofi().BuscarNVC(NVC, baseDatosUsuario());

            if (nvc != null)
            {
                NVCL = nvc;
            }
            else
            {
                ViewBag.mensaje = 1;
                ViewBag.NVnum = _nvId;
                return Json(new { Mensaje = ViewBag.mensaje, nvNum = ViewBag.NVnum });
            }

            ViewBag.cabecera = NVCL;

            var nvd = controlDisofi().BuscarNVD(NVD, baseDatosUsuario());

            if (nvd != null)
            {
                NVDL = nvd;
            }

            ViewBag.detalle = NVDL;

            return Json(new { Cabecera = NVCL, Detalle = NVDL, Mensaje = ViewBag.mensaje, NVNumero = ViewBag.NVnum }, JsonRequestBehavior.AllowGet);
        }

        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.ADMINISTRADOR, PERFILES.APROBADOR, PERFILES.VENDEDOR)]
        public ActionResult FacturasAprobadas()
        {
            ParametrosModels parametros = ObtieneParametros();

            ViewBag.Parametros = parametros;

            List<NotadeVentaCabeceraModels> doc = new List<NotadeVentaCabeceraModels>();
            string codigoVendedor = obtenerUsuario().TipoUsuario == Convert.ToInt32(PERFILES.APROBADOR) ? "-1" : codigoVendedorUsuario();
            var docAprobados = controlDisofi().listarDocAprobados(baseDatosUsuario(), EmpresaUsuario().IdEmpresa, codigoVendedor);


            if (docAprobados != null)
            {
                doc = docAprobados;
            }

            ViewBag.doc = doc;

            return View();
        }

        [HttpPost]
        public JsonResult FacturasAprobadas(int _nvId)
        {
            NotadeVentaCabeceraModels NVC = new NotadeVentaCabeceraModels();
            List<NotadeVentaCabeceraModels> NVCL = new List<NotadeVentaCabeceraModels>();
            NotaDeVentaDetalleModels NVD = new NotaDeVentaDetalleModels();
            List<NotaDeVentaDetalleModels> NVDL = new List<NotaDeVentaDetalleModels>();

            NVC.Id = _nvId;
            NVD.Id = _nvId;

            var nvc = controlDisofi().BuscarNVC(NVC, baseDatosUsuario());

            if (nvc != null)
            {
                NVCL = nvc;
            }
            else
            {
                ViewBag.mensaje = 1;
                ViewBag.NVnum = _nvId;
                return Json(new { Mensaje = ViewBag.mensaje, nvNum = ViewBag.NVnum });
            }

            ViewBag.cabecera = NVCL;

            var nvd = controlDisofi().BuscarNVD(NVD, baseDatosUsuario());

            if (nvd != null)
            {
                NVDL = nvd;
            }

            ViewBag.detalle = NVDL;

            return Json(new { Cabecera = NVCL, Detalle = NVDL, Mensaje = ViewBag.mensaje, NVNumero = ViewBag.NVnum }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        [HttpPost]
        public JsonResult ModificarProductoNuevo(string CodProdAntiguo, int IdDetalle, string CodProd, string DesProd, string CodGrupo, string CodSubGr, decimal PrecioVenta, string CodMon)
        {
            RespuestaModel respuesta = controlDisofi().InsertarProductoNuevoDisofi(baseDatosUsuario(), CodProdAntiguo, CodProd, DesProd, CodGrupo, CodSubGr, PrecioVenta, CodMon);
            RespuestaModel respuesta2 = controlDisofi().ActualizaNotaVentaProductoNuevo(baseDatosUsuario(), IdDetalle, CodProd);

            return Json(respuesta);
        }

        [HttpPost]
        public JsonResult AprobarNotaVenta(int _nvId)
        {
            NotadeVentaCabeceraModels notaVenta = new NotadeVentaCabeceraModels();

            ParametrosModels para = ObtieneParametros();
            notaVenta.Id = _nvId;

            NotaDeVentaDetalleModels NVD = new NotaDeVentaDetalleModels();
            NVD.Id = _nvId;



            List<NotaDeVentaDetalleModels> nvd = controlDisofi().BuscarNVD(NVD, baseDatosUsuario());
            RespuestaModel respuesta = new RespuestaModel();
            respuesta.Verificador = true;
            respuesta.Mensaje = "";

            for (int x = 0; x < nvd.Count; x++)
            {
                if (nvd[x].EsProductoNuevo)
                {
                    if (respuesta.Verificador)
                    {
                        respuesta = controlDisofi().InsertarProductoNuevoSoftland(baseDatosUsuario(), nvd[x].CodProd);
                    }
                }
            }


            if (respuesta.Verificador)
            {
                NotadeVentaCabeceraModels cabecera = controlDisofi().GetCab(_nvId);

                RespuestaModel resp = controlDisofi().InsertarClientesSoftland(cabecera.CodAux.ToString(), baseDatosUsuario());
                List<NotadeVentaCabeceraModels> proceso = controlDisofi().actualizaEstado(notaVenta, baseDatosUsuario());

                DireccionDespachoModels direc = new DireccionDespachoModels();
                direc.CodAxD = cabecera.CodAux.ToString();

                //Se lista(n) la(s) dirección(es) de despacho
                string direccionDx = "Sin Direccion";
                LogUser.agregarLog(cabecera.CodLugarDesp);

                if(cabecera.CodLugarDesp != null && cabecera.CodLugarDesp != "Sin Direccion")
                {
                    List<DireccionDespachoModels> direccion = controlDisofi().BuscarDirecDespachMail(direc, baseDatosUsuario(), cabecera.CodLugarDesp);
                    direccionDx = direccion[0].NomDch + ", " + direccion[0].ComDes + ", " + direccion[0].CiuDes;
                }

                List<string> paraEmail = new List<string>();



                var IdAprobador = SessionVariables.SESSION_DATOS_USUARIO.UsuarioEmpresaModel.IdEmpresa;

                RespuestaModel grabaAprobadoPor = controlDisofi().grabaAprobadoPor(proceso[0].NVNumero,_nvId, IdAprobador, proceso[0].IdEmpresaInterna,"A");

                List<VendedorModels> vendedores = controlDisofi().GetVendedores(baseDatosUsuario(), new VendedorModels { VenCod = cabecera.VenCod });

                foreach (var item in vendedores)
                {
                    LogUser.agregarLog("VENDEDORES---" + item.Email.ToString());
                }

                List<AprobadorModels> aprobador = controlDisofi().GetAprobador(IdAprobador);

                foreach (var item in aprobador)
                {
                    LogUser.agregarLog("APROBADORES---" + item.email.ToString());

NotaVenta/Views/Cotizacion/MisClientes.cshtml
@using UTIL.Models;
@using NotaVenta.UTIL;
@{
    string parametroUpdate = NotaVenta.UTIL.ActualizacionJS.obtenerParametro();
    ViewBag.Title = "Mis Clientes";
    List<ClientesModels> clientes = ViewBag.clientes;
    ParametrosModels parametros = ViewBag.parametros;
    if (((BaseController)this.ViewContext.Controller).codigoVendedorUsuario() == null)
    {
        var URL = System.Configuration.ConfigurationManager.AppSettings.Get("url");
        Response.Redirect(URL);
    }
}

<link href="~/Scripts/css/estilotables.css" rel="stylesheet" />
<script src="~/WebJs/Cotizacion/MisClientes.js" ?@parametroUpdate></script>
<style>
    .rojomaldito {
        background: #E49685;
        color: black;
    }
</style>
<body class="contact-page">
    <input type="hidden" id="urlTablaSaldos" value="@Url.Action("ObtenerSaldo", "Reporte")" />
    <div id="content" class="content">
        <input type="hidden" id="urlNotaVenta" value="@Url.Action("Cotizacion", "Cotizacion" )" />
        <h1 class="page-header">@ViewBag.Message <small></small></h1>
        <div class="panel panel-inverse width-full">
            <div class="panel-heading">
                <h4 class="panel-title">Listado De Clientes </h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                </div>
            </div>
            <div class="table-responsive">
                @if (parametros.AgregaCliente)
                {
                    <div class="float-right">
                        <br />
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#AgregaCliente">Agregar Cliente</button>
                        <br />
                        <br />
                    </div>
                }
                <table id="dataTable" class="table" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Codigo</th>
                            <th>Cliente</th>
                            <th>Dirección</th>
                            <th>Telefono</th>
                            <th>Notas</th>
                            <th>Cotizacion</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            try
                            {
                                for (int i = 0; i < clientes.Count; i++)
                                {
                                    <tr>
                                        <td>@clientes[i].CodAux</td>
                                        <td>@clientes[i].NomAux</td>
                                        <td>@clientes[i].DirAux @clientes[i].DirNum</td>
                                        <td>@clientes[i].FonAux1</td>


                                        @if (clientes[i].Notas == null)
                                        {
                                            <td>No cuenta con nota</td>
                                        }
                                        else
                                        {
                                            <td>@clientes[i].Notas</td>
                                        }
                                        <td>
                                            <a class="btn btn-default btn-xs" onclick="PreNotaVenta('@clientes[i].CodAux','@clientes[i].NomAux', '@clientes[i].RutAux')" style="cursor:pointer;" />
                                            <img src="~/Content/Image/guia.png" />
                                            @*<a class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalSaldo" onclick="ObtenerSaldo('@clientes[i].RutAux')" style="cursor:pointer;" />
                                                <img src="~/Content/Image/guia.png" />*@
                                        </td>
                                    </tr>
                                }
                            }
                            catch (Exception)
                            {
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td>Este Usuario no tiene Clientes Asociados</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <div id="AgregaCliente" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Agregar Cliente</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="x_content">
                        <br />
                        <div class="form-horizontal form-label-left input_mask">
                            <input type="hidden" name="txtcodAux" id="CodAuxMod">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                                    <label class="control-label"><b>Rut: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="text" required="required" maxlength="12" class="form-control has-feedback-left" id="RutCli" name="txtNombre" placeholder="Rut" oninput="checkRut(this)" maxlength="13">
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6">
                                    <label class="control-label"><b>Giro Cliente: </b></label>
                                    @Html.DropDownList("GirAux", (IEnumerable<SelectListItem>)ViewBag.Giro, "Seleccione Giro", new { @class = "form-control", @id = "GirAux", @name = "GirAux" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                                    <label class="control-label"><b>Nombre: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="text" required="required" maxlength="60" class="form-control has-feedback-left" id="NombreCli" name="txtUsuario" placeholder="Nombre">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                                    <label class="control-label"><b>Email: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="email" required class="form-control" maxlength="250" id="EmailMod" name="EmailCli" placeholder="Email">
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-6 form-group has-feedback">
                                    <label class="control-label"><b>Email Dte: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="email" required class="form-control" maxlength="250" id="EmailDteMod" name="EmailCli" placeholder="Email">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback">
                                    <label class="control-label"><b>Direccion: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="text" required class="form-control" maxlength="60" id="DireccioCli" name="Direccion" placeholder="Direccion">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-xs-4 form-group has-feedback">
                                    <label class="control-label"><b>Telefono: </b></label>
                                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                                    <input type="tel" required class="form-control" maxlength="15" id="TelefonoCli" name="Telefono" placeholder="Telefono">
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-4 form-group has-feedback">
                                    <label class="control-label"><b>Ciudad: </b></label>
                                    @Html.DropDownList("AgregarClienteCiudad", (IEnumerable<SelectListItem>)ViewBag.Ciudad, "Seleccione Ciudad", new { @class = "form-control", @id = "AgregarClienteCiudad", @name = "AgregarClienteCiudad" })
                                </div>
                                <div class="col-md-4 col-sm-4 col-xs-4 form-group has-feedback">
                                    <label class="control-label"><b>Comuna: </b></label>
                                    @Html.DropDownList("AgregarClienteComuna", (IEnumerable<SelectListItem>)ViewBag.Comuna, "Seleccione Comuna", new { @class = "form-control", @id = "AgregarClienteComuna", @name = "AgregarClienteComuna" })
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                                    <button class="btn btn-success" type="submit" id="AgregarCliente" onclick="AgregarCliente()">Grabar</button>
                                    <button class="btn btn-primary" type="reset" style="display: none">Resetear</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnCerrarModal" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>


    <a id="AgregarCorreo" style="display: none" href="#modalAddCorreo" class="btn btn-sm btn-success" data-toggle="modal">prueba</a>
    <div class="modal fade" id="modalAddCorreo">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Cliente no tiene Correo Asociado</h4>
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">
                        x
                    </button>
                </div>
                <div class="modal-body">
                    <div class="table-responsive form-inline">
                        <table class="table ">
                            <tbody>
                                <tr class="highlighted">
                                    <td>Agregar Correo:</td>
                                    <td><input type="email" required id="AddCorreo" name="AddCorreo" class="form-control" /></td>
                                </tr>
                            </tbody>
                            <tr>
                                <td></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <a id="btnAgregarCorreo" href="javascript:;" class="btn btn-success">Confirmar</a>
                    <a id="CerrarAddCorreo" href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
                </div>
            </div>
        </div>
    </div>

    <div id="modalSaldo" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Detalle Saldo Cliente</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="x_content">
                        <div class="col-lg-push-12">
                            <div class="table-responsive form-inline">
                                <table id="tblSaldos" class="table table-profile"></table>
                            </div>
                        </div>
                        <br />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnCerrarModal" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

</body>