NotaVenta/Controllers/MantenedorComisionesController.cs
using NotaVenta.UTIL;
using NotaVenta.UTIL.FilterAttributes;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UTIL.Models;


namespace TexasHub.Controllers
{
    public class MantenedorComisionesController : BaseController
    {
        // GET: MantenedorComisiones
        [Autorizacion(PERFILES.SUPER_ADMINISTRADOR, PERFILES.COMISIONES, PERFILES.REPORTES)]
        public ActionResult MantenedorComisiones()
        {
            return View();
        }

        public JsonResult UploadVentas()
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    HttpFileCollectionBase file = Request.Files;

                    if (file != null && file.Count > 0)
                    {
                        byte[] fileBytes = new byte[Request.ContentLength];
                        var data = Request.InputStream.Read(fileBytes, 0, Convert.ToInt32(Request.ContentLength));

                        ExcelPackage.LicenseContext = LicenseContext.Commercial;

                        //hacer for para recorrer archivo y guardar por linea
                        using (var package = new ExcelPackage(Request.InputStream))
                        {
                            var currentSheet = package.Workbook.Worksheets;
                            var workSheet = currentSheet.First();

                            for (int i = 3; i <= workSheet.Dimension.End.Row; i++)
                            {
                                if (workSheet.Cells[i, 3].Value == null) { break; }
                                VendedorComision VendedorCom = new VendedorComision();

                                try
                                {
                                    VendedorCom.CodigoVendedor = workSheet.Cells[i, 1].Value.ToString();
                                    VendedorCom.Nombre = workSheet.Cells[i, 2].Value.ToString();
                                    VendedorCom.lp1 = double.Parse(workSheet.Cells[i, 3].Value.ToString());
                                    VendedorCom.lp2 = double.Parse(workSheet.Cells[i, 4].Value.ToString());
                                    VendedorCom.lp3 = double.Parse(workSheet.Cells[i, 5].Value.ToString());
                                    VendedorCom.lp4 = double.Parse(workSheet.Cells[i, 6].Value.ToString());

                                    RespuestaModels response = controlDisofi().GrabarComision(VendedorCom);
                                    if (!response.Verificador)
                                    {
                                        return Json(new RespuestaModels { Verificador = false, Mensaje = "Problemas Con Insercion" });
                                    }
                                }
                                catch (Exception e)
                                {
                                    package.Dispose();
                                    string error = e.Message.ToString();
                                    return Json(new RespuestaModels { Verificador = false, Mensaje = "Problemas Con el Archivo" });
                                }
                            }

                        }

                    }
                }
                catch (Exception e)
                {
                    string error = e.Message.ToString();
                    //UTIL.LogUser.agregarLog(error);
                    return Json(new { Verificador = false, Mensaje = "Debe Cargar un Archivo" });
                }
            }
            return Json(new RespuestaModels { Verificador = true, Mensaje = "Archivo Cargado" });
        }




    }
}

NotaVenta/Controllers/MantenedorController.cs
using NotaVenta.UTIL;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UTIL.Models;
using UTIL.Objetos;

namespace TexasHub.Controllers
{
    public class MantenedorController : BaseController
    {
        #region ValorMoneda
        // GET: Mantenedor
        public ActionResult ValorMoneda()
        {
            ViewBag.Monedas = controlDisofi().ListarMonedas(baseDatosUsuario());
            return View();
        }
        #endregion

        #region Consideraciones
        public ActionResult Consideraciones()
        {
            ViewBag.Consideraciones = controlDisofi().ListarConsideraciones();
            return View();
        }

        public JsonResult GrabarConsideracion(string titulo,string consideracion)
        {
            RespuestaModel respuesta = new RespuestaModel();
            respuesta = controlDisofi().GrabarConsideracion(titulo, consideracion);

            List<ConsideracionesModel> consideraciones = new List<ConsideracionesModel>();
            consideraciones = controlDisofi().ListarConsideraciones();
            return Json(new {respuesta, consideraciones = consideraciones });
        }

        public JsonResult ModificarConsideracion(int id,string titulo, string consideracion)
        {
            RespuestaModel respuesta = new RespuestaModel();
            respuesta =controlDisofi().ModificarConsideracion(id,titulo, consideracion);
            List<ConsideracionesModel> consideraciones = new List<ConsideracionesModel>();
            consideraciones = controlDisofi().ListarConsideraciones();
            return Json(new {respuesta, consideraciones = consideraciones });
        }

        public JsonResult EliminarConsideracion(int id)
        {

            RespuestaModel respuesta = new RespuestaModel();
            respuesta = controlDisofi().EliminarConsideracion(id);
            List<ConsideracionesModel> consideraciones = new List<ConsideracionesModel>();
            consideraciones = controlDisofi().ListarConsideraciones();

            return Json(new {respuesta, consideraciones = consideraciones });
        }

        #endregion

        #region CargarArchivo
        public ActionResult CargarArchivo()
        {
            return View();
        }
        public JsonResult UploadPRoductos()
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    HttpFileCollectionBase file = Request.Files;

                    if (file != null && file.Count > 0)
                    {
                        byte[] fileBytes = new byte[Request.ContentLength];
                        var data = Request.InputStream.Read(fileBytes, 0, Convert.ToInt32(Request.ContentLength));

                        ExcelPackage.LicenseContext = LicenseContext.Commercial;

                        //hacer for para recorrer archivo y guardar por linea
                        using (var package = new ExcelPackage(Request.InputStream))
                        {
                            var currentSheet = package.Workbook.Worksheets;
                            var workSheet = currentSheet.First();

                            for (int i = 3; i <= workSheet.Dimension.End.Row; i++)
                            {
                                ProductosMatenedorModel producto = new ProductosMatenedorModel();
                                try
                                {
                                    producto.Codigo = workSheet.Cells[i, 1].Value.ToString();
                            //        VendedorCom.Nombre = workSheet.Cells[i, 2].Value.ToString();
                            //        VendedorCom.lp1 = double.Parse(workSheet.Cells[i, 3].Value.ToString());
                            //        VendedorCom.lp2 = double.Parse(workSheet.Cells[i, 4].Value.ToString());
                            //        VendedorCom.lp3 = double.Parse(workSheet.Cells[i, 5].Value.ToString());
                            //        VendedorCom.lp4 = double.Parse(workSheet.Cells[i, 6].Value.ToString());

                                   RespuestaModel response = controlDisofi().GrabarProducto(producto);
                            //        if (!response.Verificador)
                            //        {
                            //            return Json(new RespuestaModel { Verificador = false, Mensaje = "Problemas Con Insercion" });
                            //        }
                                }
                                catch (Exception e)
                                {
                            //        package.Dispose();
                                    string error = e.Message.ToString();
                            //        return Json(new RespuestaModel { Verificador = false, Mensaje = "Problemas Con el Archivo" });
                                }
                            }

                        }

                    }
                }
                catch (Exception e)
                {
                    string error = e.Message.ToString();
                    //UTIL.LogUser.agregarLog(error);
                    return Json(new { Verificador = false, Mensaje = "Debe Cargar un Archivo" });
                }
            }
            return Json(new RespuestaModel { Verificador = true, Mensaje = "Archivo Cargado" });
        }
        #endregion
    }
}

NotaVenta/Views/Mantenedor/CargarArchivo.cshtml
@{
    ViewBag.Title = "CargarArchivo";
}

<form name="form_COnvertirdorArchivos" method="post" class="col-md-12" id="ff" action="" enctype="multipart/form-data">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Cargar Archivo</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th><label for="File">Cargar Archivo: </label></th>
                <th><input type="file" class="upload" name="UploadedFile" id="fileLoadDoc" accept=".xls, .xlsx" /></th>
                <th><button class="btn btn-primary btn-lg btn-block" id="btnUpFile" style="cursor: pointer;" />Cargar </th>
            </tr>
            <tr></tr>
        </tbody>
    </table>
</form>
      <script>
        var formdata = new FormData();
        var banderaArchivo = 0;
        $(function () {
            $('#btnUpFile').click(function () {
                if ($('#selectArea').val() == 0 || banderaArchivo == 0) {
                    alert("Favor seleccionar Area o seleccionar archivo");
                } else {
                    var Files = $("#fileLoadDoc").get(0);
                    activarLoadingBoton('btnUpFile');
                $.ajax({
                    url: '@Url.Action("UploadVentas", "MantenedorComisiones")',
                    type: "POST",
                    datatype: "JSON",
                    contentType: false,
                    processData: false,
                    data: formdata,
                    success: function (result) {
                        if (result.Verificador) {
                            desactivarLoadingBoton('btnUpFile');
                            fileLoad();
                            banderaArchivo = 0;
                            abrirConfirmacion("Usuario", result.Mensaje);
                        }
                        else
                        {
                            desactivarLoadingBoton('btnUpFile');
                            abrirError("Usuario", result.Mensaje);
                        }
                    }
                })}
            });
        });


               function fileLoad() {
            $('#txtfile').val("");
            $('#fileLoadDoc').val("");
            $('#btnFileLoad').val("");
            
        };

            $('input[type="file"]').change(function (e) {
                formdata = new FormData();
                var filename = e.target.files[0].name;
            $("#txtfile").val(filename);
            for (var i = 0; i < e.target.files.length; i++) {
               formdata.append(e.target.files[i].name, e.target.files[i]);
            }
            banderaArchivo = 1;
            });

          
</script>

NotaVenta/Views/Mantenedor/Consideraciones.cshtml
@using UTIL.Models;
@using UTIL.Objetos;
@using NotaVenta.UTIL;
@{
    string parametroUpdate = NotaVenta.UTIL.ActualizacionJS.obtenerParametro();
    ViewBag.Title = "Consideraciones";
    List<UTIL.Models.ConsideracionesModel> consideraciones = ViewBag.Consideraciones;
}

<script src="~/WebJs/Mantenedor/Mantenedores.js"@parametroUpdate></script>

<div class="row col-lg-12">
    <div class="col-lg-12">
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Consideraciones
                </h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>
            </div>
            <div class="panel-body">
                <div class="float-lg-right">
                    <br />
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#AgregaConsideracion" onclick="limpiarAgregar()">Agregar</button>
                    <br />
                    <br />
                </div>
                <div class="table-responsive form-inline">

                    <table id="detalle" class="table table-condensed table-bordered ">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Titulo</th>
                                <th style=" width: 650px !important">Consideracion</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                                @for (int x = 0; x < consideraciones.Count; x++)
                                {
                                 <tr>
                                    <td id="filaId_@x">@(consideraciones[x].Id)</td>
                                    <td id="filaTitulo_@x">@(consideraciones[x].Titulo)</td>
                                    @if (consideraciones[x].Consideracion.Length > 275)
                                    {
                                        <td id="Consideracion">@(consideraciones[x].Consideracion.Substring(0, 275) + "...")</td>

                                        <td hidden id="filaConsideracion_@x">@(consideraciones[x].Consideracion)</td>
                                    }
                                    else
                                    {
                                        <td id="filaConsideracion_@x">@(consideraciones[x].Consideracion)</td>
                                    }
                                <td>
                                    <input class="btn btn-primary" type="button" name="Editar"  value="Editar" onclick="MostarDatos(@consideraciones[x].Id, @x);">
                                </td>
                                <td>
                                    <input class="btn btn-primary" type="button" name="Eliminar" value="Eliminar" onclick="EliminarConsideracion(@consideraciones[x].Id);">
                                </td>
                                </tr>
                                }
                            
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="AgregaConsideracion" style="height: 100%">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Agregar Consideracion de la Empresa</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-1">
                        <span>Titulo</span>
                    </div>
                    <div class="col-lg-4">
                        <input type="text" id="modelTitulo" maxlength="200" class="form-control" rows="10"/>
                    </div>
                    <div class="col-sm-8">
                        <span>Descripcion</span>
                    </div>
                    <div class="col-lg-12">
                        <textarea id="modelDescripcion" maxlength="2000" class="form-control" rows="10"></textarea>
                    </div>
                </div>
            </div> 
            <div class="modal-footer">
                <button id="modalAgregarConsideracion" onclick="GrabarConsideracion()" class="btn btn-success">Aceptar</button>
                <a id="modalAgregarProductoNuevoCerrar" href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="modalModificarConsideracion" style="height: 100%">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Agregar Consideracion de la Empresa</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <input type="text" id="editarId" class="form-control" hidden readonly/>
                <div class="row">
                    <div class="col-sm-1">
                        <span>Titulo</span>
                    </div>
                    <div class="col-lg-4">
                        <input type="text" id="editarTitulo" class="form-control"/>
                    </div>
                    <div class="col-sm-8">
                        <span>Descripcion</span>
                    </div>
                    <div class="col-lg-12">
                        <textarea id="editarDescripcion" maxlength="2000" class="form-control" rows="10"></textarea>
                    </div>
                </div>
            </div> 
            <div class="modal-footer">
                <button id="modalAgregarConsideracion" onclick="ModificarConsideracion()" class="btn btn-success">Aceptar</button>
                <a id="modalAgregarProductoNuevoCerrar" href="javascript:;" class="btn btn-white" data-dismiss="modal">Cerrar</a>
            </div>
        </div>
    </div>
</div>

NotaVenta/Views/Mantenedor/ValorMoneda.cshtml
@using UTIL.Models;
@using UTIL.Objetos;
@using NotaVenta.UTIL;
@{
    ViewBag.Title = "ValorMoneda";


    List<UTIL.Models.MonedaModel> monedas = ViewBag.Monedas;
}


 <div class="row col-lg-12">
        <div class="col-lg-12">
            <div class="panel panel-inverse">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Valor monedas
                    </h4>
                    <div class="panel-heading-btn">
                        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="table-responsive form-inline">
                        <table class="table table-profile">
                            <tbody>
                                <tr class="highlight">
                                    <td>Tipo de Moneda</td>
                                    <td>
                                        <select id="TipoMoneda" class="form-control">
                                            @for (int x = 0; x < monedas.Count; x++)
                                            {
                                                <option value="@(monedas[x].CodigoMoneda)">@(monedas[x].SimboloMoneda + " - " + monedas[x].DescripcionMoneda)</option>
                                            }
                                        </select>
                                    </td>
                                </tr>
                                <tr class="highlight">
                                    <td nowrap="nowrap">Valor Moneda</td>
                                    <td>
                                        <input type="text" name="txtcontacto" id="txtcontacto" class="form-control" value="Sin Contacto" tabindex="-1" />
                                    </td>                                    
                                </tr>
                                <tr  class="highlight">
                                    <td></td>
                                    <td>
                                        <input type="button" id="btnGrabar" class="btn btn-primary" value="Guardar" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
          
             